//go:build wasip1

// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     ffrwd:av@0.19.1

package ffrwd_av_node

import (
	"github.com/imbcmdth/ffrwd-node/go/internal/wit/ffrwd_av_node_tick"
	"github.com/imbcmdth/ffrwd-node/go/internal/wit/ffrwd_av_node_types"
	"github.com/imbcmdth/ffrwd-node/go/internal/wit/ffrwd_av_types"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

type Meta = ffrwd_av_types.Meta
type Packet = ffrwd_av_types.Packet
type RawFrame = ffrwd_av_types.RawFrame
type Binding = ffrwd_av_node_types.Binding
type BoundStream = ffrwd_av_node_types.BoundStream
type Message = ffrwd_av_node_types.Message
type NodeShape = ffrwd_av_node_types.NodeShape
type Tick = ffrwd_av_node_tick.Tick

// An input frame's bytes leaving on an output, never copied into the
// module: frame `index` of stream `id`'s `frames` this tick. Its format
// must be the port's (size and pixel format, or sample format, rate and
// channels); the host ends the run otherwise. Audio may leave this way
// only from an input whose stride is its window, since overlapping
// windows would emit samples twice.
type SameFrame struct {
	Pts      int64
	Duration witTypes.Option[int64]
	Id       uint32
	Index    uint32
}

const (
	// New bytes in the port's format: one frame's pixels, tightly packed,
	// or a run of interleaved samples.
	PayloadFrame uint8 = 0
	PayloadSame  uint8 = 1
	// For codec "json", one UTF-8 JSON object. Empty: a progress mark,
	// never delivered; the port's progress stands at its pts.
	PayloadMessage uint8 = 2
	PayloadPacket  uint8 = 3
)

// One thing leaving. Its pts and duration are in its port's time base,
// and the module's to choose.
type Payload struct {
	tag   uint8
	value any
}

func (self Payload) Tag() uint8 {
	return self.tag
}

func (self Payload) Frame() ffrwd_av_types.RawFrame {
	if self.tag != PayloadFrame {
		panic("tag mismatch")
	}
	return self.value.(ffrwd_av_types.RawFrame)
}
func (self Payload) Same() SameFrame {
	if self.tag != PayloadSame {
		panic("tag mismatch")
	}
	return self.value.(SameFrame)
}
func (self Payload) Message() ffrwd_av_node_types.Message {
	if self.tag != PayloadMessage {
		panic("tag mismatch")
	}
	return self.value.(ffrwd_av_node_types.Message)
}
func (self Payload) Packet() ffrwd_av_types.Packet {
	if self.tag != PayloadPacket {
		panic("tag mismatch")
	}
	return self.value.(ffrwd_av_types.Packet)
}

func MakePayloadFrame(value ffrwd_av_types.RawFrame) Payload {
	return Payload{PayloadFrame, value}
}
func MakePayloadSame(value SameFrame) Payload {
	return Payload{PayloadSame, value}
}
func MakePayloadMessage(value ffrwd_av_node_types.Message) Payload {
	return Payload{PayloadMessage, value}
}
func MakePayloadPacket(value ffrwd_av_types.Packet) Payload {
	return Payload{PayloadPacket, value}
}

type Emission struct {
	// An output's name in the node's shape.
	Port    string
	Payload Payload
}

// What one tick produced.
type Emitted struct {
	// Per port, frames and messages never go back in pts, within a call
	// or across calls, and packets keep decode order with dts never
	// decreasing. Ports interleave freely.
	Items []Emission
	// Rows for the run's rows output, as a sink's are.
	Rows []string
	// Nothing more will leave: the host makes the last call and then ends
	// every output. A node on an input clock ends with that input and need
	// not set it.
	Finished bool
}
