//go:build wasip1

// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     ffrwd:av@0.19.1

package ffrwd_av_node_types

import (
	"github.com/imbcmdth/ffrwd-node/go/internal/wit/ffrwd_av_types"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

type Rational = ffrwd_av_types.Rational
type ColorInfo = ffrwd_av_types.ColorInfo
type VideoFormat = ffrwd_av_types.VideoFormat
type AudioFormat = ffrwd_av_types.AudioFormat
type CodedStream = ffrwd_av_types.CodedStream
type Packet = ffrwd_av_types.Packet
type StreamInfo = ffrwd_av_types.StreamInfo
type RenditionMeta = ffrwd_av_types.RenditionMeta
type Wants = ffrwd_av_types.Wants

const (
	PortKindVideo   uint8 = 0
	PortKindAudio   uint8 = 1
	PortKindData    uint8 = 2
	PortKindPackets uint8 = 3
)

type PortKind = uint8

const (
	RowsUseIgnore   uint8 = 0
	RowsUsePerFrame uint8 = 1
	RowsUseState    uint8 = 2
)

// What a node does with the rows that arrive on an input.
// `per-frame`: reads a tick's rows while handling that tick and keeps
// nothing. `state`: folds rows into state later ticks depend on, so a
// frame-parallel instance must also see the rows of the ticks it did not
// process (`earlier-rows`).
type RowsUse = uint8

const (
	AnchorSharedClock uint8 = 0
	AnchorFirstFrame  uint8 = 1
	AnchorTagged      uint8 = 2
)

// How a hold input's offset between source time and clock time is fixed.
// `shared-clock`: the source's pts are on the clock's epoch; offset 0, and
// the host holds the first frame until the clock reaches it (a timed
// feeder). `first-frame`: the offset is fixed once the host holds `lead`
// seconds of the source, or its end, and the start is scheduled `lead`
// seconds ahead of the clock (an untimed feeder). `tagged`: shared-clock
// for a feed whose tags carry this name set to 1, first-frame
// otherwise (the switch's `smart_timed`).
type Anchor struct {
	tag   uint8
	value any
}

func (self Anchor) Tag() uint8 {
	return self.tag
}

func (self Anchor) Tagged() string {
	if self.tag != AnchorTagged {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeAnchorSharedClock() Anchor {
	return Anchor{AnchorSharedClock, nil}
}
func MakeAnchorFirstFrame() Anchor {
	return Anchor{AnchorFirstFrame, nil}
}
func MakeAnchorTagged(value string) Anchor {
	return Anchor{AnchorTagged, value}
}

// A frame input paired by time: the newest frame at or before the tick.
// The host keeps the source buffered ahead, repeats the last frame while
// the source falls behind, skips forward when it catches up, and reports
// both. What ffrwd/switch did for itself, for any node.
type Hold struct {
	Anchor Anchor
	// Seconds ahead of the clock a first-frame start is scheduled.
	Lead float64
	// Seconds the last frame stays after the source ends; none drops it
	// at once.
	Linger witTypes.Option[float64]
	// Seconds of programme time without a frame before a live source is
	// given up on and its feed ended; none waits for it.
	Timeout witTypes.Option[float64]
	// Hold inputs of one group arrive on one connection from one source
	// (a feeder's picture and sound): one offset, fixed by the group's
	// first picture, and feed starts and ends on the same tick.
	Group witTypes.Option[string]
	// The param that carries this input's loopback port. Bound to a
	// stream, the host writes the port it picked there; left unbound, the
	// host listens on the port the call wrote, and whatever connects is
	// the source.
	PortParam witTypes.Option[string]
}

// A message input paired by time: every message whose pts falls in the
// tick's interval, extended by `ahead`, each delivered once at the first
// tick that holds it, held while it is ahead of the clock. The host
// settles the interval once the producer's progress has passed its end
// plus `ahead`; `latency` bounds that wait, and a message later than the
// bound is delivered at the next tick and reported.
type Interval struct {
	// The most this input waits, in seconds: the interval settles once the
	// clock input has arrived this long past its end, progress or not.
	// None waits for the producer's progress alone; a producer that sends
	// none (a lateral, a data feeder) needs a bound set.
	Latency witTypes.Option[float64]
	// Seconds past the interval's end whose messages are handed with it,
	// for a node that acts before a stamp (a fade in before a cue).
	Ahead float64
	// What maps the stream's pts onto the clock. `shared-clock`: the
	// stream counts on the clock's origin, as a lateral's rows do.
	// `first-frame`: the first message is placed at the tick it arrives
	// on and the offset holds for the stream's life, every message
	// re-stamped onto the clock's time base (a data stream on another
	// time origin, which ffrwd/playout's `follow` re-stamped by hand).
	// `tagged`: shared-clock when the stream's tags carry the name set
	// to 1, first-frame otherwise.
	Anchor Anchor
	// Names a hold group: this stream arrives on that group's
	// connection, with the group's offset, fixed by its first picture (a
	// data stream a feeder writes beside its picture and sound). Paired
	// by interval as any data input is. With a group, `anchor` is
	// `shared-clock`.
	Group witTypes.Option[string]
}

const (
	// The clock's pts exactly: same source, one frame per tick. The input
	// `clock` names is declared lockstep.
	PairingLockstep uint8 = 0
	// Frame kinds only.
	PairingHold uint8 = 1
	// Message kinds only.
	PairingInterval uint8 = 2
	// Delivered as it arrives, unpaired: packets to a sink, data a node
	// orders itself.
	PairingArrival uint8 = 3
)

type Pairing struct {
	tag   uint8
	value any
}

func (self Pairing) Tag() uint8 {
	return self.tag
}

func (self Pairing) Hold() Hold {
	if self.tag != PairingHold {
		panic("tag mismatch")
	}
	return self.value.(Hold)
}
func (self Pairing) Interval() Interval {
	if self.tag != PairingInterval {
		panic("tag mismatch")
	}
	return self.value.(Interval)
}

func MakePairingLockstep() Pairing {
	return Pairing{PairingLockstep, nil}
}
func MakePairingHold(value Hold) Pairing {
	return Pairing{PairingHold, value}
}
func MakePairingInterval(value Interval) Pairing {
	return Pairing{PairingInterval, value}
}
func MakePairingArrival() Pairing {
	return Pairing{PairingArrival, nil}
}

// What an input accepts. Empty lists accept anything of the kind.
type Accepts struct {
	PixelFormats  []string
	SampleFormats []string
	SampleRates   []uint32
	ChannelCounts []uint32
	Codecs        []string
	Wants         ffrwd_av_types.Wants
	// Conformed by the host to that input's stream: a video to its size,
	// an audio to its rate and layout. The named input is single.
	Like witTypes.Option[string]
}

type InputPort struct {
	Name     string
	Kind     PortKind
	Required bool
	// Any number of streams bound to this one port, each with its own
	// metadata and time base (a publisher's renditions, a weave's rows
	// inputs).
	Many    bool
	Pairing Pairing
	Rows    RowsUse
	// The clock input: frames (video) or samples (audio) a call sees, and
	// how many it consumes. Every other input hands the tick's interval
	// and declares 1/1.
	Window  uint32
	Stride  uint32
	Accepts Accepts
	// Data inputs: the JSON schema of the rows the node reads here, as
	// `rows-module` declared its input rows. None accepts any row.
	Schema witTypes.Option[string]
}

// An input's format with one field overridden: a matte the size of its
// picture, in gray. The named input is single and a frame kind.
type LikeInput struct {
	Port         string
	PixelFormat  witTypes.Option[string]
	SampleFormat witTypes.Option[string]
}

const (
	OutputFormatVideo uint8 = 0
	OutputFormatAudio uint8 = 1
	// The codec, "json" today.
	OutputFormatData    uint8 = 2
	OutputFormatPackets uint8 = 3
	OutputFormatLike    uint8 = 4
)

type OutputFormat struct {
	tag   uint8
	value any
}

func (self OutputFormat) Tag() uint8 {
	return self.tag
}

func (self OutputFormat) Video() ffrwd_av_types.VideoFormat {
	if self.tag != OutputFormatVideo {
		panic("tag mismatch")
	}
	return self.value.(ffrwd_av_types.VideoFormat)
}
func (self OutputFormat) Audio() ffrwd_av_types.AudioFormat {
	if self.tag != OutputFormatAudio {
		panic("tag mismatch")
	}
	return self.value.(ffrwd_av_types.AudioFormat)
}
func (self OutputFormat) Data() string {
	if self.tag != OutputFormatData {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self OutputFormat) Packets() ffrwd_av_types.CodedStream {
	if self.tag != OutputFormatPackets {
		panic("tag mismatch")
	}
	return self.value.(ffrwd_av_types.CodedStream)
}
func (self OutputFormat) Like() LikeInput {
	if self.tag != OutputFormatLike {
		panic("tag mismatch")
	}
	return self.value.(LikeInput)
}

func MakeOutputFormatVideo(value ffrwd_av_types.VideoFormat) OutputFormat {
	return OutputFormat{OutputFormatVideo, value}
}
func MakeOutputFormatAudio(value ffrwd_av_types.AudioFormat) OutputFormat {
	return OutputFormat{OutputFormatAudio, value}
}
func MakeOutputFormatData(value string) OutputFormat {
	return OutputFormat{OutputFormatData, value}
}
func MakeOutputFormatPackets(value ffrwd_av_types.CodedStream) OutputFormat {
	return OutputFormat{OutputFormatPackets, value}
}
func MakeOutputFormatLike(value LikeInput) OutputFormat {
	return OutputFormat{OutputFormatLike, value}
}

type OutputPort struct {
	Name string
	Kind PortKind
	// None: the clock input's format, as most filters leave it.
	Format witTypes.Option[OutputFormat]
	// None: the clock input's.
	TimeBase witTypes.Option[ffrwd_av_types.Rational]
	// How far behind the end of its tick's interval a stamp may fall, in
	// seconds; 0 when everything leaves with its tick. A window's
	// length is not counted here: a recogniser that emits a window's
	// results with the window declares 0. Consumers pairing by interval
	// and the compiler's delay sums read it.
	Latency float64
	// Data outputs: the JSON schema of the rows this port writes.
	Schema witTypes.Option[string]
	// A source read in FROM: the row of `relation` this output belongs
	// to. Outputs of one row are one rendition.
	Row witTypes.Option[uint32]
}

const (
	ClockInput uint8 = 0
	// A generator: ticks at this rate, paced to real time in a live run
	// and as fast as the outputs drain otherwise. For a node with inputs
	// that only need turns (a publisher's network session): at least this
	// often, and the last call comes once every input has ended, unless
	// the node finished first.
	ClockRate uint8 = 1
	// A rate clock at the named input's rate, which the compiler reads
	// off that port's first stream; the input itself is held like any
	// other. A tile of pictures at the first picture's rate.
	ClockRateOf uint8 = 2
	// The node emits when it has something; its outputs' pts are the
	// timeline (a network source).
	ClockSelfClocked uint8 = 3
)

type Clock struct {
	tag   uint8
	value any
}

func (self Clock) Tag() uint8 {
	return self.tag
}

func (self Clock) Input() string {
	if self.tag != ClockInput {
		panic("tag mismatch")
	}
	return self.value.(string)
}
func (self Clock) Rate() ffrwd_av_types.Rational {
	if self.tag != ClockRate {
		panic("tag mismatch")
	}
	return self.value.(ffrwd_av_types.Rational)
}
func (self Clock) RateOf() string {
	if self.tag != ClockRateOf {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeClockInput(value string) Clock {
	return Clock{ClockInput, value}
}
func MakeClockRate(value ffrwd_av_types.Rational) Clock {
	return Clock{ClockRate, value}
}
func MakeClockRateOf(value string) Clock {
	return Clock{ClockRateOf, value}
}
func MakeClockSelfClocked() Clock {
	return Clock{ClockSelfClocked, nil}
}

// What the compiler knows of one stream before the run.
type StreamHint struct {
	// Video: the frame rate. Audio: the sample rate over 1. None where
	// nothing settles it before the run (a self-clocked source's output,
	// a feed by port).
	Rate witTypes.Option[ffrwd_av_types.Rational]
}

// One input a call binds, as `shape` is told it.
type Binding struct {
	// The input, by the declaration's name.
	Input string
	// The streams the call binds here, in the order it names them, one
	// hint each: how many a many port takes, and the clock's rate, so a
	// latency or a window known in frames or samples is declared in
	// seconds exactly.
	Streams []StreamHint
}

type NodeShape struct {
	Inputs  []InputPort
	Outputs []OutputPort
	Clock   Clock
	// Every call depends only on what it was handed, counting a state
	// input's earlier rows as handed. A host spreads a pure node over
	// workers; an impure one runs as one instance, in order.
	Pure bool
	// Frame kinds: one frame out per frame in on the clock's outputs, each at
	// its tick's pts. Audio: samples conserved and contiguous.
	OneToOne bool
	// A rate or self-clocked node: whether it ends by itself. A live one
	// does not, and the compiler plans it as live. Ignored on an input
	// clock.
	Bounded bool
	// A source read in FROM: one JSON object per relation row (rendition,
	// bandwidth, codecs, geometry), which its outputs name by index.
	Relation []string
}

// One stream bound to an input port at `init`.
type BoundStream struct {
	Port string
	// Names the stream for the instance's life: distinct across the
	// bound streams, and what every tick call and `same` take.
	Id uint32
	// Its time base is `info.time-base`.
	Info ffrwd_av_types.StreamInfo
	// The format the stream arrives in, resolved: never `like`. Packets
	// inputs carry `coded`.
	Format    witTypes.Option[OutputFormat]
	Rendition ffrwd_av_types.RenditionMeta
	// The relation row the stream came from, where the call reads rows (a
	// sink handed a ladder); the publisher names its tracks by it.
	Row witTypes.Option[uint32]
	// Packets inputs: how deep the stream reorders, as `input-stream`
	// carries it at 0.18. 0 elsewhere.
	DecodeDelay uint32
	// Data inputs: the producer's declared latency, when it has one.
	Latency witTypes.Option[float64]
	// The hint `shape` was asked with for this stream, so an instance
	// that derives its shape again at `init` derives the one the plan
	// was made from.
	Hint StreamHint
}

type Message struct {
	Pts  int64
	Data []uint8
}

type TimedRows struct {
	Pts  int64
	Rows []string
}

type FeedStart struct {
	// The source's tags, `smart_timed` among them.
	Tags []witTypes.Tuple2[string, string]
	// Its first frame's pts, in its own time base.
	FirstPts int64
	// The clock time that first frame stands at, in the clock's time base:
	// what maps the source's pts onto the tick.
	At int64
	// The clock time of the tick the start was fixed on: when the first
	// frame arrived and the offset was settled, which for a timed source
	// is seconds before `at`; equal to `at` when fixed on the tick it
	// showed. What a countdown counts from.
	Known int64
}

// A hold input's feed: one source, from the tick its first frame shows
// on to the last its last frame shows on, `linger` included. The source
// going backwards, or forwards by more than a second, ends it and
// starts the next.
type Feed struct {
	Start FeedStart
	// The clock time of the last tick its last frame shows on, once the
	// host can foretell it: the source ended, or timed out.
	Ends witTypes.Option[int64]
}

// One frame as a tick sees it, without its bytes: a picture, or the
// tick's audio samples as one run, which is a frame as codecs count
// them.
type Frame struct {
	// In the stream's time base; for audio, the first sample's.
	Pts int64
	// Its place in the stream's `frames` this tick, oldest first from 0:
	// what `fetch` and `same` name it by.
	Index uint32
	// How long it is presented, in the stream's time base; none where
	// nothing settles it.
	Duration witTypes.Option[int64]
	// The rows that arrived with it, each a JSON object from an upstream
	// module. Empty on an input whose `rows` is `ignore`.
	Rows []string
}
