//go:build wasip1

// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     ffrwd:av@0.19.1

package ffrwd_av_node_tick

import (
	"github.com/imbcmdth/ffrwd-node/go/internal/wit/ffrwd_av_node_types"
	"github.com/imbcmdth/ffrwd-node/go/internal/wit/ffrwd_av_types"
	witRuntime "go.bytecodealliance.org/pkg/wit/runtime"
	witTypes "go.bytecodealliance.org/pkg/wit/types"
	"runtime"
	"unsafe"
)

type Rational = ffrwd_av_types.Rational
type Packet = ffrwd_av_types.Packet
type StreamInfo = ffrwd_av_types.StreamInfo
type Frame = ffrwd_av_node_types.Frame
type Message = ffrwd_av_node_types.Message
type Feed = ffrwd_av_node_types.Feed
type TimedRows = ffrwd_av_node_types.TimedRows

//go:wasmimport ffrwd:av/node-tick@0.19.1 [resource-drop]tick
func resourceDropTick(handle int32)

// One call's inputs, held by the host for exactly that call. A stream
// is named by the `id` `init` gave it; an id `init` did not give, or an
// index at or past the length of that stream's `frames`, is a
// fault that stops the run.
//
// The tick's interval runs from its time to the next tick's: one stride
// of a frame clock, one packet of a packets clock, every message
// sharing one pts of a data clock, one period of a rate clock. A last
// call's runs to the end of its inputs. Every input that is not the
// clock hands what falls in it.
//
// The handle is the call's alone: it cannot be kept past the return,
// and bytes a module means to keep are its own copy the moment `fetch`
// hands them over.
type Tick struct {
	handle *witRuntime.Handle
}

func (self *Tick) TakeHandle() int32 {
	return self.handle.Take()
}

func (self *Tick) SetHandle(handle int32) {
	self.handle.Set(handle)
}

func (self *Tick) Handle() int32 {
	return self.handle.Use()
}

func (self *Tick) Drop() {
	handle := self.handle.TakeOrNil()
	if handle != 0 {
		resourceDropTick(handle)
	}
}

func TickFromOwnHandle(handleValue int32) *Tick {
	handle := witRuntime.MakeHandle(handleValue)
	value := &Tick{handle}
	runtime.AddCleanup(value, func(_ int) {
		handleValue := handle.TakeOrNil()
		if handleValue != 0 {
			resourceDropTick(handleValue)
		}
	}, 0)
	return value
}

func TickFromBorrowHandle(handleValue int32) *Tick {
	handle := witRuntime.MakeHandle(handleValue)
	return &Tick{handle}
}

//go:wasmimport ffrwd:av/node-tick@0.19.1 [method]tick.pts
func wasm_import_method_tick_pts(arg0 int32) int64

func (self *Tick) Pts() int64 {

	result := wasm_import_method_tick_pts((self).Handle())
	return result

}

//go:wasmimport ffrwd:av/node-tick@0.19.1 [method]tick.ordinal
func wasm_import_method_tick_ordinal(arg0 int32) int64

func (self *Tick) Ordinal() uint64 {

	result := wasm_import_method_tick_ordinal((self).Handle())
	return uint64(result)

}

//go:wasmimport ffrwd:av/node-tick@0.19.1 [method]tick.time-base
func wasm_import_method_tick_time_base(arg0 int32, arg1 uintptr)

func (self *Tick) TimeBase() ffrwd_av_types.Rational {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, 8, 4))
	wasm_import_method_tick_time_base((self).Handle(), returnArea)
	result := ffrwd_av_types.Rational{*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 0)), *(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 4))}
	return result

}

//go:wasmimport ffrwd:av/node-tick@0.19.1 [method]tick.last
func wasm_import_method_tick_last(arg0 int32) int32

func (self *Tick) Last() bool {

	result := wasm_import_method_tick_last((self).Handle())
	return (result != 0)

}

//go:wasmimport ffrwd:av/node-tick@0.19.1 [method]tick.streams
func wasm_import_method_tick_streams(arg0 int32, arg1 uintptr, arg2 uint32, arg3 uintptr)

func (self *Tick) Streams(port string) []uint32 {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	utf8 := unsafe.Pointer(unsafe.StringData(port))
	pinner.Pin(utf8)
	wasm_import_method_tick_streams((self).Handle(), uintptr(utf8), uint32(len(port)), returnArea)
	value := unsafe.Slice((*uint32)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result := value
	return result

}

//go:wasmimport ffrwd:av/node-tick@0.19.1 [method]tick.info
func wasm_import_method_tick_info(arg0 int32, arg1 int32, arg2 uintptr)

func (self *Tick) Info(id uint32) ffrwd_av_types.StreamInfo {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (32 + 6*4), 8))
	wasm_import_method_tick_info((self).Handle(), int32(id), returnArea)
	value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (2 * 4))))
	value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (3 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (4 * 4))))
	var option witTypes.Option[float64]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 4*4)))) {
	case 0:

		option = witTypes.None[float64]()
	case 1:

		option = witTypes.Some[float64](*(*float64)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 4*4))))
	default:
		panic("unreachable")
	}
	result := make([]witTypes.Tuple2[string, string], 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 5*4))))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 5*4)))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 4*4))))), index*(4*4))
		value1 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
		value2 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

		result = append(result, witTypes.Tuple2[string, string]{value1, value2})
	}

	result3 := ffrwd_av_types.StreamInfo{uint32(*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), 0))), value, value0, option, result, ffrwd_av_types.Rational{*(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 6*4))), *(*int32)(unsafe.Add(unsafe.Pointer(returnArea), (28 + 6*4)))}}
	return result3

}

//go:wasmimport ffrwd:av/node-tick@0.19.1 [method]tick.feed
func wasm_import_method_tick_feed(arg0 int32, arg1 int32, arg2 uintptr)

func (self *Tick) Feed(id uint32) witTypes.Option[ffrwd_av_node_types.Feed] {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (48 + 2*4), 8))
	wasm_import_method_tick_feed((self).Handle(), int32(id), returnArea)
	var option1 witTypes.Option[ffrwd_av_node_types.Feed]
	switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))) {
	case 0:

		option1 = witTypes.None[ffrwd_av_node_types.Feed]()
	case 1:
		result := make([]witTypes.Tuple2[string, string], 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 1*4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 8)))), index*(4*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

			result = append(result, witTypes.Tuple2[string, string]{value, value0})
		}

		var option witTypes.Option[int64]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), (32 + 2*4)))) {
		case 0:

			option = witTypes.None[int64]()
		case 1:

			option = witTypes.Some[int64](*(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (40 + 2*4))))
		default:
			panic("unreachable")
		}

		option1 = witTypes.Some[ffrwd_av_node_types.Feed](ffrwd_av_node_types.Feed{ffrwd_av_node_types.FeedStart{result, *(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (8 + 2*4))), *(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (16 + 2*4))), *(*int64)(unsafe.Add(unsafe.Pointer(returnArea), (24 + 2*4)))}, option})
	default:
		panic("unreachable")
	}
	result2 := option1
	return result2

}

//go:wasmimport ffrwd:av/node-tick@0.19.1 [method]tick.ended-feeds
func wasm_import_method_tick_ended_feeds(arg0 int32, arg1 int32, arg2 uintptr)

func (self *Tick) EndedFeeds(id uint32) []ffrwd_av_node_types.Feed {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_tick_ended_feeds((self).Handle(), int32(id), returnArea)
	result1 := make([]ffrwd_av_node_types.Feed, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0)))), index*(40+2*4))
		result := make([]witTypes.Tuple2[string, string], 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0)))), index*(4*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))
			value0 := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (3 * 4))))

			result = append(result, witTypes.Tuple2[string, string]{value, value0})
		}

		var option witTypes.Option[int64]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (24 + 2*4)))) {
		case 0:

			option = witTypes.None[int64]()
		case 1:

			option = witTypes.Some[int64](*(*int64)(unsafe.Add(unsafe.Pointer(base), (32 + 2*4))))
		default:
			panic("unreachable")
		}

		result1 = append(result1, ffrwd_av_node_types.Feed{ffrwd_av_node_types.FeedStart{result, *(*int64)(unsafe.Add(unsafe.Pointer(base), (2 * 4))), *(*int64)(unsafe.Add(unsafe.Pointer(base), (8 + 2*4))), *(*int64)(unsafe.Add(unsafe.Pointer(base), (16 + 2*4)))}, option})
	}

	result2 := result1
	return result2

}

//go:wasmimport ffrwd:av/node-tick@0.19.1 [method]tick.frames
func wasm_import_method_tick_frames(arg0 int32, arg1 int32, arg2 uintptr)

func (self *Tick) Frames(id uint32) []ffrwd_av_node_types.Frame {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_tick_frames((self).Handle(), int32(id), returnArea)
	result0 := make([]ffrwd_av_node_types.Frame, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0)))), index*(32+2*4))
		var option witTypes.Option[int64]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 16))) {
		case 0:

			option = witTypes.None[int64]()
		case 1:

			option = witTypes.Some[int64](*(*int64)(unsafe.Add(unsafe.Pointer(base), 24)))
		default:
			panic("unreachable")
		}
		result := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (32 + 1*4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (32 + 1*4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 32)))), index*(2*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result = append(result, value)
		}

		result0 = append(result0, ffrwd_av_node_types.Frame{*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)), uint32(*(*int32)(unsafe.Add(unsafe.Pointer(base), 8))), option, result})
	}

	result1 := result0
	return result1

}

//go:wasmimport ffrwd:av/node-tick@0.19.1 [method]tick.fetch
func wasm_import_method_tick_fetch(arg0 int32, arg1 int32, arg2 int32, arg3 uintptr)

func (self *Tick) Fetch(id uint32, index uint32) []uint8 {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_tick_fetch((self).Handle(), int32(id), int32(index), returnArea)
	value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	result := value
	return result

}

//go:wasmimport ffrwd:av/node-tick@0.19.1 [method]tick.messages
func wasm_import_method_tick_messages(arg0 int32, arg1 int32, arg2 uintptr)

func (self *Tick) Messages(id uint32) []ffrwd_av_node_types.Message {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_tick_messages((self).Handle(), int32(id), returnArea)
	result := make([]ffrwd_av_node_types.Message, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0)))), index*(8+2*4))
		value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))

		result = append(result, ffrwd_av_node_types.Message{*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)), value})
	}

	result0 := result
	return result0

}

//go:wasmimport ffrwd:av/node-tick@0.19.1 [method]tick.packets
func wasm_import_method_tick_packets(arg0 int32, arg1 int32, arg2 uintptr)

func (self *Tick) Packets(id uint32) []ffrwd_av_types.Packet {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_tick_packets((self).Handle(), int32(id), returnArea)
	result := make([]ffrwd_av_types.Packet, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0)))), index*(48+2*4))
		var option witTypes.Option[int64]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8))) {
		case 0:

			option = witTypes.None[int64]()
		case 1:

			option = witTypes.Some[int64](*(*int64)(unsafe.Add(unsafe.Pointer(base), 16)))
		default:
			panic("unreachable")
		}
		var option0 witTypes.Option[int64]
		switch uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 24))) {
		case 0:

			option0 = witTypes.None[int64]()
		case 1:

			option0 = witTypes.Some[int64](*(*int64)(unsafe.Add(unsafe.Pointer(base), 32)))
		default:
			panic("unreachable")
		}
		value := unsafe.Slice((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (40 + 1*4)))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), (40 + 2*4))))

		result = append(result, ffrwd_av_types.Packet{*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)), option, option0, (uint8(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 40))) != 0), value})
	}

	result1 := result
	return result1

}

//go:wasmimport ffrwd:av/node-tick@0.19.1 [method]tick.earlier-rows
func wasm_import_method_tick_earlier_rows(arg0 int32, arg1 int32, arg2 uintptr)

func (self *Tick) EarlierRows(id uint32) []ffrwd_av_node_types.TimedRows {
	pinner := &runtime.Pinner{}
	defer pinner.Unpin()

	returnArea := uintptr(witRuntime.Allocate(pinner, (2 * 4), 4))
	wasm_import_method_tick_earlier_rows((self).Handle(), int32(id), returnArea)
	result0 := make([]ffrwd_av_node_types.TimedRows, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4)))
	for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 4))); index++ {
		base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(returnArea), 0)))), index*(8+2*4))
		result := make([]string, 0, *(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4))))
		for index := 0; index < int(*(*uint32)(unsafe.Add(unsafe.Pointer(base), (8 + 1*4)))); index++ {
			base := unsafe.Add(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 8)))), index*(2*4))
			value := unsafe.String((*uint8)(unsafe.Pointer(uintptr(*(*uint32)(unsafe.Add(unsafe.Pointer(base), 0))))), *(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)))

			result = append(result, value)
		}

		result0 = append(result0, ffrwd_av_node_types.TimedRows{*(*int64)(unsafe.Add(unsafe.Pointer(base), 0)), result})
	}

	result1 := result0
	return result1

}
