//go:build wasip1

// Generated by `wit-bindgen` 0.59.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     ffrwd:av@0.19.1

package ffrwd_av_types

import (
	witTypes "go.bytecodealliance.org/pkg/wit/types"
)

// Static description of a module, available without running anything.
type Meta struct {
	Name    string
	Version string
	// JSON Schema for the `params` string.
	ParamsSchema string
	// JSON Schema for one row object; empty when the module emits none.
	RowsSchema string
	// Pixel formats accepted, most preferred first. Empty means this is not
	// a video module.
	PixelFormats []string
	// Sample formats accepted, most preferred first: "f32" or "s16", always
	// interleaved. Empty means this is not an audio module. A module is one
	// kind or the other, so exactly one of this and `pixel-formats` is
	// filled in.
	SampleFormats []string
	// Sample rates accepted. Empty is every rate.
	SampleRates []uint32
	// Channel counts accepted. Empty is every count.
	ChannelCounts []uint32
	// Ordered param names; the module's rows' language is the first of these
	// params that is set at the call; empty list = none declared.
	RowsLanguage []string
}

// A ratio of two whole numbers.
type Rational struct {
	Num int32
	Den int32
}

// A stream's colorimetry, in ffmpeg's own names: "tv" or "pc" for the
// range, "bt709" and the like for the rest. A field the wire does not
// settle is "unknown", ffmpeg's own spelling for it.
type ColorInfo struct {
	Range     string
	Primaries string
	Trc       string
	Space     string
}

// The frames of a video instance, fixed for the life of the instance.
// Frames cross this boundary square-pixel: the host rescales anamorphic
// input before it arrives, so no aspect ratio is carried here.
type VideoFormat struct {
	Width  uint32
	Height uint32
	PixFmt string
	// The colorimetry the stream header declared; none where it did not.
	Color witTypes.Option[ColorInfo]
}

// The samples of an audio instance, fixed for the life of the instance.
type AudioFormat struct {
	SampleRate uint32
	Channels   uint32
	// "f32" or "s16", interleaved.
	SampleFmt string
	// ffmpeg's name for the channel layout ("stereo", "5.1"), which a
	// count alone cannot say; none where the wire does not carry one.
	ChannelLayout witTypes.Option[string]
}

const (
	FormatVideo uint8 = 0
	FormatAudio uint8 = 1
)

// What an instance is opened for, which is what tells its kind. A module
// is handed the arm its own declaration asked for; the host refuses the
// other one before `init`.
type Format struct {
	tag   uint8
	value any
}

func (self Format) Tag() uint8 {
	return self.tag
}

func (self Format) Video() VideoFormat {
	if self.tag != FormatVideo {
		panic("tag mismatch")
	}
	return self.value.(VideoFormat)
}
func (self Format) Audio() AudioFormat {
	if self.tag != FormatAudio {
		panic("tag mismatch")
	}
	return self.value.(AudioFormat)
}

func MakeFormatVideo(value VideoFormat) Format {
	return Format{FormatVideo, value}
}
func MakeFormatAudio(value AudioFormat) Format {
	return Format{FormatAudio, value}
}

// The stream an instance is attached to, told once at init.
type StreamInfo struct {
	Index uint32
	Kind  string
	Codec string
	// Seconds; absent when unknown.
	Duration witTypes.Option[float64]
	// The stream's own tags.
	Tags []witTypes.Tuple2[string, string]
	// The unit timestamps are counted in, as a fraction of a second. The host
	// always supplies it; `den` is always positive. A windowed module is
	// handed timestamps rather than seconds, so this is how one whose
	// parameters are in seconds converts them. For audio it is what turns a
	// sample position into a timestamp: at 1/48000 one tick is one sample.
	TimeBase Rational
}

// The frames a coded video stream declares. Shared between `packet-sink`
// and `packet-source`.
type CodedVideo struct {
	Width  uint32
	Height uint32
	// The pixel aspect ratio the stream declares. Packets cannot be
	// host-rescaled, so a packager writes it through (mp4's `pasp`);
	// none where the wire does not say.
	SampleAspectRatio witTypes.Option[Rational]
	// The colorimetry the stream header declared; none where it did not.
	Color witTypes.Option[ColorInfo]
}

// The samples a coded audio stream declares.
type CodedAudio struct {
	SampleRate uint32
	Channels   uint32
	// ffmpeg's name for the channel layout ("stereo", "5.1"), which a
	// count alone cannot say; none where the wire does not carry one.
	ChannelLayout witTypes.Option[string]
}

const (
	CodedFormatVideo uint8 = 0
	CodedFormatAudio uint8 = 1
	// A data stream: messages rather than pictures or sound, each packet
	// one message at its own pts. For codec "json" a message is one UTF-8
	// JSON object. It has no geometry, and every packet is a keyframe.
	CodedFormatData uint8 = 2
)

// What a coded stream carries, which is what tells its kind.
type CodedFormat struct {
	tag   uint8
	value any
}

func (self CodedFormat) Tag() uint8 {
	return self.tag
}

func (self CodedFormat) Video() CodedVideo {
	if self.tag != CodedFormatVideo {
		panic("tag mismatch")
	}
	return self.value.(CodedVideo)
}
func (self CodedFormat) Audio() CodedAudio {
	if self.tag != CodedFormatAudio {
		panic("tag mismatch")
	}
	return self.value.(CodedAudio)
}

func MakeCodedFormatVideo(value CodedVideo) CodedFormat {
	return CodedFormat{CodedFormatVideo, value}
}
func MakeCodedFormatAudio(value CodedAudio) CodedFormat {
	return CodedFormat{CodedFormatAudio, value}
}
func MakeCodedFormatData() CodedFormat {
	return CodedFormat{CodedFormatData, nil}
}

// One encoded stream an instance is opened for, fixed for its life.
type CodedStream struct {
	// ffmpeg's name for the codec, e.g. "h264".
	Codec string
	// The unit `pts` and `dts` are counted in, as a fraction of a second.
	TimeBase Rational
	// The geometry the stream declares, and its kind.
	Format CodedFormat
	// The codec's out-of-band header, exactly as the stream header carried
	// it: for h264, the SPS and PPS a downstream packager needs before the
	// first packet.
	Extradata []uint8
	// The codec's profile, in the codec's own numbering - what ffmpeg's
	// codec parameters carry; none where the wire does not say.
	Profile witTypes.Option[int32]
	// The codec's level, likewise.
	Level witTypes.Option[int32]
}

// One encoded packet, exactly as the encoder emitted it.
type Packet struct {
	// When the picture is presented, in the stream's time base. Packets
	// arrive in decode order, so where the stream reorders frames this is
	// not monotonic.
	Pts int64
	// When the packet is decoded; never decreasing. Absent for the first
	// packets of a reordering stream, where the wire does not settle it.
	Dts witTypes.Option[int64]
	// How long the packet is presented, in the stream's time base: the
	// next packet's pts minus this one's, in presentation order. None
	// where the wire does not settle it - unknown is never spelled 0.
	Duration witTypes.Option[int64]
	// Whether decoding can start at this packet.
	Keyframe bool
	// The encoded bytes, untouched.
	Data []uint8
}

// One raw frame crossing a codec: a video frame's pixels in the
// instance's pix-fmt, or a run of interleaved audio samples in its
// sample-fmt. What a codec and a node hand over.
type RawFrame struct {
	// When it is presented, in the stream's time base.
	Pts int64
	// How long it is presented, in the stream's time base; none where
	// nothing settles it - unknown is never spelled 0.
	Duration witTypes.Option[int64]
	Data     []uint8
}

// One pad's packets from one call, in decode order. Empty when nothing
// arrived on that pad; a packet sink's list of these is as long as its
// `init`'s streams and in the same order, so the index is the pad.
type PadPackets struct {
	Packets []Packet
}

// What the source read of one relation row: a rendition's name, bitrate
// and codec string, exactly as the manifest or catalog said them. None
// where nothing said so. Shared between `packet-sink` and
// `packet-source`.
type RenditionMeta struct {
	Name      witTypes.Option[string]
	Bandwidth witTypes.Option[uint64]
	Codecs    witTypes.Option[string]
	Language  witTypes.Option[string]
}

const (
	// Every packet of every stream. What a sink that counts, tallies or
	// republishes needs, and what a host with no way to skip hands over.
	WantsAll uint8 = 0
	// The keyframes, and whatever else the host could not cheaply drop.
	// What a sink reading data a writer placed on keyframes needs.
	WantsKeyframes uint8 = 1
	// The first packet of each stream, and no more. What a sink reading
	// only what a stream declares about itself needs.
	WantsFirst uint8 = 2
	// A node's frame input read for its frames' times and its stream's
	// info alone, never their bytes: `fetch` on it is a fault. The
	// compiler hands the stream in whatever format its source has
	// cheapest, and the host carries no pixels or samples for it (a mask
	// sized and timed by a picture it never reads). Frame kinds only.
	WantsTiming uint8 = 3
)

// How much of a stream a sink has to be handed to do its work. A sink
// that reads what a writer put on keyframes, or what a stream's first
// packet declares, does not need the rest - and a host reading a file to
// answer a question at compile time can copy far less of it.
//
// It is a REQUEST, not a promise: a host may hand over more than was
// asked for, and every sink has to work when it does. What a host may not
// do is hand over less.
type Wants = uint8

const (
	// None of this kind reaches the module.
	ArityZero uint8 = 0
	// Exactly one, which is what every sink before 0.12.0 read.
	ArityOne uint8 = 1
	// One or more, as many as the query hands over.
	ArityMany uint8 = 2
	// As many as the query hands over, none included: the module reads
	// them when they are there and works when they are not.
	ArityAny uint8 = 3
)

// How many streams of one kind a module reading encoded packets takes.
// Shared between `packet-sink` and `packet-filter`.
type Arity = uint8

// One pad's stream, told once at init: what the wire's own header said
// about the encoding, and what the process driving the host said about
// the stream. Shared between `packet-sink` and `packet-filter`.
type InputStream struct {
	Coded CodedStream
	Info  StreamInfo
	// Which relation row this pad belongs to - the moq sink learns
	// renditions from the rows instead of from argument names.
	Row uint32
	// What the source read of that row.
	Rendition RenditionMeta
	// How deep this stream reorders: how many packets the decoder holds
	// back before the first picture leaves it. 0 where decode order IS
	// presentation order, and higher wherever B-frames do.
	//
	// It is the bound a module that must see packets in PRESENTATION
	// order works with: a packet's presentation successor has arrived
	// once `decode-delay` more packets have. It is also why `packet.dts`
	// is none for a pad's first `decode-delay` packets, which is the wire
	// not having settled them rather than the host withholding them.
	DecodeDelay uint32
}
